name       : perl-eval-closure
version    : 0.14
release    : 3
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DO/DOY/Eval-Closure-0.14.tar.gz : ea0944f2f5ec98d895bef6d503e6e4a376fea6383a6bc64c7670d46ff2218cad
license    : Artistic-2.0
component  : programming.perl
summary    : Safely and cleanly create closures via string eval
description: |
    Safely and cleanly create closures via string eval
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
